kind: Secret
apiVersion: v1
metadata:
  namespace: "{{ .Values.namespace }}"
  name: app-secrets
immutable:
  true
data:
  {{- range $key, $value := .Values.app.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
