apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: app-service
spec:
  selector:
    app: app-service
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.app.service_port }}
      targetPort: {{ .Values.app.container_port }}
