---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rki-lk-dashboard-user
  namespace: rki-lk-dashboard

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rki-lk-dashboard-user-full-access
  namespace: rki-lk-dashboard
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rki-lk-dashboard-user-binding
  namespace: rki-lk-dashboard
subjects:
- kind: ServiceAccount
  name: rki-lk-dashboard-user
  namespace: rki-lk-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rki-lk-dashboard-user-binding
